### ISSUE TITLE
Options instead of props as second argument to render 

### ISSUE THREAD

**Issue by EmilTholin** [testing-library/svelte-testing-library#1]
Thank you for you hard work on `svelte-testing-library`! I can't wait to test my components with this!

What are your thoughts about changing the second argument of `render` to `options` instead of `props`? This would allow the user of this great library to tailor [all the other component options that are available to their liking, most notably `hydrate`](https://svelte.dev/docs#Creating_a_component).

```diff
- export const render = (Component, props) => {
+ export const render = (Component, options) => {
    const container = document.body.appendChild(document.createElement('div'))

    const rendered = new Component({
+     ...options,
      target: container,
-     props,
    })
    // ...
  }
```

```javascript
const { getByText } = render(App, {
  props: { name: "world" },
  hydrate: true
});
```

**Comment by benmonro** [comment]
I dig it, @EmilTholin.  makes sense to me.

I noticed you have a library as well.  I had googled 'svelte-testing-library' before starting this repo, and didn't see anything, so just dove in. Then I noticed that you and another person have started work on these.  Feel free to submit PRs!

-Ben

**Comment by EmilTholin** [comment]
Great!

It might be worth contacting Wendell to see if he wants to join forces on this repository. It would be a shame if we spread our efforts on three almost identical projects, and the offical `testing-library` version didn't get the `svelte-testing-library` name.

**Comment by benmonro** [comment]
I did reach out to Wendell but haven't heard back, and I'd love to join forces and agree 💯
