### ISSUE TITLE
Cleanup targets as well as components

### ISSUE THREAD

**Issue by EmilTholin** [testing-library/svelte-testing-library#10]
The great `cleanup` function destroys all the created components, but the targets are still around. What do you think about extending the `cleanupAtContainer` function to remove the `target` DOM nodes that were created as childen of `body`, [like `react-testing-library` does](https://github.com/testing-library/react-testing-library/blob/960451b00196352fc3085a3d1bb233b5b85f454b/src/index.js#L91-L97)?

```diff
 export const render = (Component, options) => {
   // ...

-  mountedContainers.add(component)
+  mountedContainers.add({target, component})

   // ...
 }

- const cleanupAtContainer = container => {
+ const cleanupAtContainer = obj => {
+   const {target, component} = obj
-   container.$destroy()
+   component.$destroy()
+   if (target.parentNode === document.body) {
+     document.body.removeChild(target)
+   }
-   mountedContainers.delete(container)
+   mountedContainers.delete(obj)
  }
```

**Comment by benmonro** [comment]
Sure!
