### ISSUE TITLE
Problem with 'use' directive (tippy.js): Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Dan1ve** [testing-library/svelte-testing-library#109]
Hi,
I recently added the [svelte-tippy](https://github.com/mdauner/sveltejs-tippy) library to my project, which is invoked with a `use` directive:

``` javascript
import tippy from 'sveltejs-tippy';
```

``` html
<div use:tippy={{ ... }}></div>
```

It seems this breaks the existing tests, which now fail with this error:
`TypeError: Cannot read property 'call' of undefined`  (followed by an unhelpful stacktrace).

This does not occur if I removed the `use` directives. Is there something that can be done about this?

**Comment by benmonro** [comment]
@Dan1ve would love a PR of you want to fix this issue.  @mihar-22  any ideas about this?

**Comment by MirrorBytes** [comment]
@Dan1ve Quick question, can you provide the useless stacktrace? This could point to an issue in jsdom or svelte itself.

**Comment by Dan1ve** [comment]
@benmonro I gave it a quick try but without luck. [Here is a PR with a failing test case](https://github.com/testing-library/svelte-testing-library/pull/114) for the scenario I mentioned. (I had to add the actual library, because simple `use:` directives seem to work fine).

The crash happens when calling the component constructor, in this line (`pure.js`, line 44):
``` js
const component = new ComponentConstructor(...
```
which in turn will call Svelte-specific code, as visible in the stacktrace (@MirrorBytes ) :

```
render › should ignore svelte use directives
    TypeError: Cannot read property 'call' of undefined

      at Object.mount [as m] (src/__tests__/fixtures/UseDirectiveComp.svelte:27:53)
      at mount_component (node_modules/svelte/internal/index.js:1414:26)
      at init (node_modules/svelte/internal/index.js:1503:9)
      at new UseDirectiveComp (src/__tests__/fixtures/UseDirectiveComp.svelte:68:3)
      at render (src/pure.js:44:21)
      at Object.<anonymous> (src/__tests__/render.test.js:82:5)
```

I happy to provide further information if necessary.

**Comment by MirrorBytes** [comment]
I've isolated it to being an issue with Tippy itself. The svelte version is just a wrapper that looks like this:

```javascript
function usetippy(node, props) {
  tippy(node, props);
}
```

It has to do with the version (6.0.3) of Tippy that project uses. The latest is 6.2.7; even resolving to that version causes a break. You don't need `sveltejs-tippy` at all, here's what I would do:
1. Uninstall `sveltejs-tippy`, install `tippy.js`.
2. In your `App.svelte`, add this:

```html
<style global>
...

@import 'tippy.js/dist/tippy.css';
</style>
```

3. In a helper file, add this:

```javascript
import tippy from 'tippy.js'

export function usetippy(node, props) {
  tippy(node, props)
}
```

4. Now use it `usetippy` anywhere with the use directive.

**Comment by MirrorBytes** [comment]
Version 6.0.3 of Tippy does not think that `tippy` is a function and is in fact undefined, which is where that `'call' of undefined` comes from.

**Comment by Dan1ve** [comment]
@MirrorBytes Excellent, thanks a lot! Works like a charm and one lib less in my project 🎉 

I'm using TypeScript, so in case someone needs it, this is my final version:

``` typescript
// Tooltip.ts 
import tippy, { Props } from 'tippy.js';

/** Export a 'use' directive for tooltips. Uses tippy.js internally */
export function tooltip(node: HTMLElement, props: Partial<Props>): void {
    tippy(node, props);
}
```

Usage in .svelte files:
``` html
<div tooltip={{placement: 'bottom', content: 'Tooltip'}}></div>
```

Closing this issue and the associated PR. Thanks again!

**Comment by MirrorBytes** [comment]
@Dan1ve Awesome! Glad I could help
