### ISSUE TITLE
svelte state persist between test

### ISSUE THREAD

**Issue by ritchieanesco** [testing-library/svelte-testing-library#115]
**Description**
I'm using [tinro](https://github.com/AlexxNB/tinro/issues/44)  for routing and writing tests for navigation changes. When the App component is rendered, the homepage is loaded by default however when one test simulates a navigation change to another page then this change is persisted to the next test. See below.

**Example**
```ts
import { fireEvent, render, screen, waitFor } from "@testing-library/svelte"
import App from "@/App.svelte"

it("should navigate to page b", async () => {
  render(App)
  expect(screen.getByTestId("home")).toBeInTheDocument()
  await fireEvent.click(screen.getByText("Page B"))
  await waitFor(() => expect(screen.getByTestId("page-b")).toBeInTheDocument())
})

it("should navigate to page c", async () => {
  render(App)
  // the following fails as route state persists from previous test.
  expect(screen.getByTestId("home")).toBeInTheDocument()
  await fireEvent.click(screen.getByText("Page C"))
  await waitFor(() => expect(screen.getByTestId("page-c")).toBeInTheDocument())
})

```
 
**tinro version:** 0.5.3
**svelte version:** 3.31.2
**@testing-library/svelte version**: 3.0.3

**Comment by MirrorBytes** [comment]
By "simulate", are you referring to a simple toggle of data, or a history api push? Because jsdom doesn't utilize navigation at all; it's a limitation. Here's a link: https://github.com/jsdom/jsdom#unimplemented-parts-of-the-web-platform

**Comment by ritchieanesco** [comment]
After some further investigation, it looks to be store related issue. Closing this issue.
