### ISSUE TITLE
How to test two way data-binding?

### ISSUE THREAD

**Issue by yjp20** [testing-library/svelte-testing-library#117]
As far as I can tell, just passing in a variable into the render function doesn't enable two way data binding. Despite being an anti-pattern, two-way data binding is actually useful in a lot of cases, so it would be nice if there was a way to ensure that it works.

Edit:
I suppose you could also do something like
```ts
const utils = render(Input, { value: "" });
const component = utils.component.$$;
/*
* Update component such that value = asdf
*/
expect(component.ctx[component.props["value"]]).toBe("asdf")
```

But it's a bit repetitive and there's probably at least some justification in putting in a helper function into the library (since the framework supports it after all)

**Comment by MirrorBytes** [comment]
I'm not sure how you're setting up two-way binding, but the easiest way to test it would be to use a store that you pass to the component via render, then update it. You may need to throw an `await tick()` prior to an `expect` statement though.

**Comment by yjp20** [comment]
Just to be clear, what I mean by two-way binding are the `bind:value={value}` kind of statements that svelte supports. 

I don't think passing in a store would work for me. I don't want to change how my code works to accommodate tests.

**Comment by MirrorBytes** [comment]
I understand what you mean by two way binding.. My question is how are you
going to test it without passing variables that are testable?

Two way binding is something that "just works" in the Svelte world. If you
have a local variable in your component (that isn't declared with `const`),
binding will just work.

The binding you should be testing, is when you're passing variables into a
component that are being bound internally.

**Comment by yjp20** [comment]
The binding mechanism itself is indeed something that "just works," but there are underlying mechanisms to that binding that may require testing. For example, in my codebase I have an input component (`InputDate`) which accepts a date and supports two way binding. Because the input itself is a text input, the component parses the text and changes the date accordingly, which then via the two-way binding will make whatever necessary state change in the parent component.

Again I _can_ use events and listeners, but I would like to keep a consistent API among all my input components, and having a two-way binding provides great UX especially for the base components within forms and controls. If I have no way of checking what the value of the prop is of the component, then I also essentially have no way of guaranteeing that this functionality (not the binding itself, but the translation process under the hood) works.

**Comment by janosh** [comment]
@yjp20 Did you ever find a good way to test 2-way binding?

**Comment by yjp20** [comment]
Sorry to say I havent yet.

**Comment by Shaunwild97** [comment]
Following, hopefully, someone finds a nice way to approach this problem.

**Comment by marcosmercuri** [comment]
I had a similar problem, and I solved it by creating a dummy wrapper on the SUT, that dispatches an event when the binded property changes:
```javascript
<script lang="ts">
    import { createEventDispatcher } from 'svelte';
    export let prop;
    const dispatch = createEventDispatcher();

    $: {
        dispatch('prop-changed', prop);
    }
</script>

<ComponentToTest bind:prop />
```

And then in the test, I render the wrapper and add a listener on the event, and do assertions on that.

Hope this helps someone.

**Comment by janosh** [comment]
Also worth checking out: [svelte-component-test-recipes](https://github.com/davipon/svelte-component-test-recipes) by @davipon has a section on [testing 2-way binding](https://github.com/davipon/svelte-component-test-recipes#testing-the-bind-directive-two-way-binding).

**Comment by denuser** [comment]
I have it like this. Works fine to me.
```
import { bind, binding_callbacks } from 'svelte/internal';
import { get, writable, type Writable } from 'svelte/store';
import type { SvelteComponent } from 'svelte';
          
 it('should bind value properly', async () => {
    const bindingProps = {
	    value: writable('')
    } as Record<string, Writable<unknown>>;
    
    const props = Object.fromEntries(
	    Object.keys(bindingProps).map((x) => [x, get(bindingProps[x])])
    );
    
    const { component } = render(Input, {
	    placeholder: 'Basic',
	    ...props
    });
    
    pushBindingCallbacks(component, bindingProps);
    
    expect(screen.getByPlaceholderText('Basic')).toBeInTheDocument();
    fireEvent.input(screen.getByPlaceholderText('Basic'), { target: { value: 'login' } });
    
    await waitFor(() => {
	    expect(get(bindingProps['value'])).toBe('login');
    });
});

function pushBindingCallbacks(
    component: SvelteComponent,
    bindingProps: Record<string, Writable<unknown>>
) {
    Object.entries(bindingProps).forEach(([key, valueStore]) => {
        binding_callbacks.push(() =>
	        bind(component, key, (value: string) => {
		        valueStore.set(value);
	        })
        );
    });
}
```
