### ISSUE TITLE
support context options?

### ISSUE THREAD

**Issue by cbbfcd** [testing-library/svelte-testing-library#136]
hi 👋

as the [svelte doc](https://svelte.dev/docs#Creating_a_component). 

I haven't paid attention to the progress of the release about svelte, but it seems that context configuration is already supported. 

```js
const svleteComponentOptions = ['anchor', 'props', 'hydrate', 'intro'] // add 'context' ?
```

**Comment by cbxp** [comment]
Yes, please allow context. It's a simple change that will make testing with context much easier.

**Comment by yanick** [comment]
The feature has been merged in, so closing issue.
