### ISSUE TITLE
Undocumented reserved `target` component option.

### ISSUE THREAD

**Issue by incendial** [testing-library/svelte-testing-library#154]
Hi, I have a `Button` component which has a property named `target` to configure `<a>` element `target` attribute:

```
<script lang="ts">
  export let href = '';
  export let target = '';
</script>

 <a
    class={`btn ${mod} ${size}`}
    {href}
    {target}
    on:click
  >
    <slot />
</a>
```

And when I try to render this component in a test:
```ts
const defaultProps = {
    href: 'test',
    target: '_blank',
}
render(Button, defaultProps)
```
I'm getting an error because `target` is actually a reserved prop which is [used for a different reasons](https://github.com/testing-library/svelte-testing-library/blob/master/src/pure.js#L15).

I didn't find any mention of that in the docs. Could you please point out where I can find that? Also, why it's named `target` and not somehow more private?

**Comment by jgbowser** [comment]
I don't think `target` is reserved by this library but rather by svelte itself, see the [Client-Side Component API Docs](https://svelte.dev/docs#run-time-client-side-component-api-creating-a-component). This is API is referenced in the [svelte-testing-library docs](https://testing-library.com/docs/svelte-testing-library/api#component-options) via a link to the Svelte docs.

**Comment by jgbowser** [comment]
To avoid errors in this scenario I believe you would pass in your `defaultProps` object like so:
```javascript
const defaultProps = {
    href: 'test',
    target: '_blank',
}
render(Button, defaultProps)
```

**Comment by yanick** [comment]
Yup, I think jbowser has it right. I'll close this issue, but if anybody disagree please don't hesitate to open it back again.

**Comment by incendial** [comment]
Sorry, but I think you're wrong, here is the code of **this** library extracting target https://github.com/testing-library/svelte-testing-library/blob/main/src/pure.js#L17
<img width="623" alt="Screenshot 2022-04-10 at 11 52 37" src="https://user-images.githubusercontent.com/21116742/162608348-85044d98-6a68-4c43-a0fa-6c0a1b8c510f.png">
and there is no way it'll work if I'll pass `{ props: defaultProps }`, since the code is unconditionally wraps passed options in props itself.

I'm asking to reopen this issue (have no permission to do it myself) and would suggest to reconsider api and separate target from a component props.

**Comment by incendial** [comment]
> and there is no way it'll work if I'll pass { props: defaultProps }, since the code in render function unconditionally wraps passed options in props itself.

Okay, I was wrong, I found that you have a check for props, so it will work. Thanks!
But IMO the current api is too implicit.

**Comment by yanick** [comment]
> But IMO the current api is too implicit.

Maaaaybe, but considering it's a testing library, I think it's fair. But if it's tripping you, you can always define something like this locally:

```
const myRender = ( comp, props, args, options ) => render( component, { props, ...args }, options );
```

Happy testing! .o/
