### ISSUE TITLE
Testing components with SvelteKit import aliases?

### ISSUE THREAD

**Issue by eden-omb** [testing-library/svelte-testing-library#179]
I'm really not sure if this is the correct forum for this kinda question, but I couldn't find anything and I can't think of a different place. SvelteKit has standard import aliases like `$/` and `$app/`, used all over the place when `import`ing inside `<script>`s in `.svelte` files. This is configured in `tsconfig.json` or `jsconfig.json` and somehow baked into the app.

I tried configuring Jest's babel config with [`babel-plugin-module-resolver`](https://www.npmjs.com/package/babel-plugin-module-resolver) but couldn't get it to work, presumably because it's in a script tag in the `.svelte` file. This seems to be working fine for every other purpose, and the plugin even works when I take the `import` statement outside of the `<script>`; though obviously this doesn't fix much.

Is there any known way to get this to work? Is there any better place I can ask in? Am I just confused and missing something stupid? Thanks a bunch in any case <3

My Jest `babel.js` for reference:
```js
require('@babel/register')({
  extensions: ['.js', '.svelte'],
  presets: [
    ['@babel/preset-env', {
        modules: 'auto',
    }],
  ],
  plugins: [
    ['babel-plugin-module-resolver', {
      root: '.',
      alias: {
        $: './src',
      },
    }],
  ],
})

```

**Comment by Julestblt1** [comment]
I think you need to add this configuration in the `jest.config.js` file.
Example with `$lib/` imports :
```
        moduleNameMapper: {
		'^\\$lib(.*)$': '<rootDir>/src/lib$1',
	}
```

**Comment by eden-omb** [comment]
Yes! Sorry, I was confused and using an old jasmine config -.-
