### ISSUE TITLE
Add .npmignore file

### ISSUE THREAD

**Issue by EmilTholin** [testing-library/svelte-testing-library#18]
What do you think about adding a `.npmignore` file to cut down on the files that are published to npm?

We might be able to ignore:

```
.DS_Store
node_modules
coverage
public
tests
.all-contributorsrc 
.prettierrc
.travis.yml
CODE_OF_CONDUCT.md
jest.config.js
rollup.config.js
```

**Comment by benmonro** [comment]
It's better to use the files section in package.json

**Comment by EmilTholin** [comment]
Great, I didn't know the `files` field in `package.json` did that.

Maybe we can add `src` and `dist` to the `files` array, so jump to definition in editors etc. still shows the source?
