### ISSUE TITLE
Issue with testing a component with conditionals

### ISSUE THREAD

**Issue by PClmnt** [testing-library/svelte-testing-library#183]
I have a component like so:

```
    {#if num === 0}
      <div>blah</div>
      <button on:click={increaseNum}>test</button>   
    {:else if num === 1}     
      <div>blah 1</div>
      <button on:click={increaseNum}>test 2</button>   
    {:else}
      <div>blah 2</div>
      {/if}

```

and a test like so

```
    it('checks text', async () => {
        const {getByText} = render(myComponent)
        await fireEvent.click(getByText('test'))
        
        const test = getByText("blah 1")
})
```

The fireEvent in the test for some reason does not trigger the conditional in the component. I just see the original rendered component whenever i debug. 

Any ideas on what is going on here?

**Comment by absinthetized** [comment]
Shouldn't get by text the button. It seems to me you are retrieving the div instead

**Comment by PClmnt** [comment]
@absinthetized Sorry, my example was incorrect as I was simplyfing my existing code. Changed it, there is definitely an issue there.

**Comment by PClmnt** [comment]
Closing this as the real issue lies with slots in my child component.
