### ISSUE TITLE
Any way to wait for exceptions /  promise rejections after a fireEvent.Click()?

### ISSUE THREAD

**Issue by awmcclain** [testing-library/svelte-testing-library#186]
I'm writing tests using msw and trying to deal with asynchronous click handlers -- but it's nearly impossible for me to get the tests to wait around long enough to catch exceptions or promise rejections.

My hunch is that because fireEvent is async (because it wants svelte to move forward a tick and process the updates), an async callback gets detached from the promise chain so you can't do a simple await.

Here's an example:

Test.svelte
```
<script>
  export let component;

  async function handleClick() {
    const data = await fetch("https://example.com/api/1/");
    throw new Error("Something went wrong!");
  }
</script>

<button on:click={handleClick} />
```

Test.spec.js
```
import '@testing-library/jest-dom'
import { within } from '@testing-library/dom'
import { render, fireEvent, waitFor, act } from '@testing-library/svelte'

import { rest } from 'msw'
import { setupServer } from 'msw/node'

import Test from "./Test.svelte"

// Setup the mock network server
const server = setupServer();

beforeAll(() => {
  // Establish requests interception layer before all tests.
  server.listen()
})
afterAll(() => {
  // Clean up after all tests are done, preventing this
  // interception layer from affecting irrelevant tests.
  server.close()
})

test('does not work', async () => {

  server.use(
    rest.get('https://example.com/api/1/', (req, res, ctx) => {
      return res(ctx.json({foo: 'bar'}))
    })
  )

  const { findByRole } = render(Test)

  const button = await findByRole('button')

  expect(await fireEvent.click(button)).toThrow() // fireEvent resolves and succeeds, it's the underlying handler that throws so this doesn't work
  
})
```

 
![image](https://user-images.githubusercontent.com/1161415/152857878-50bace54-66ea-4d54-a5df-b8bf4ab3b604.png)

Understandably, the test finishes before the network call finishes and the test passes (even if there exceptions on the page) -- because the test isn't able to wait for the handler to finish.

**Comment by mcous** [comment]
@awmcclain are you still experiencing issues here? Fundamentally, I think the problem here is a bit of a misunderstanding about how to properly mix one form of asynchronous code - event emitters - with another - async/await (AKA Promises). This is not unique to Svelte, this is simply how DOM events work. You _must_ handle Promise rejections in event handler callbacks yourself

To test something like a failed request, a possible strategy is to test that the error triggers some sort of error state in the UI:

```svelte
<script>
let errorMessage
let data

const fetchData = async function handleClick() {
  const response = await fetch("https://example.com/api/1/");
  throw new Error("Something went wrong!");
  return response
}

const handleClick = () => {
  fetchData()
    .then((nextData) => (data = nextData))
    .catch((error) => (errorMessage = error.message))
}
</script>

<button on:click={handleClick} />
<div role="alert" aria-label="errors">
  {#if errorMessage}
    <p>{errorMessage}</p>
  {/if}
</div>
```

```ts
test('displays error', async () => {
  render(Test)

  const button = screen.getByRole('button')
  const status = screen.getByRole('status')

  await fireEvent.click(button)

  await waitFor(() => {
    expect(status).toHaveTextContent(/something went wrong/iu)
  })
})
```

@yanick I think this issue can be closed and/or moved to a usage help discussion
