### ISSUE TITLE
Semantic Pull Requests is no longer maintained

### ISSUE THREAD

**Issue by yanick** [testing-library/svelte-testing-library#192]
https://github.com/zeke/semantic-pull-requests#readme

And indeed it doesn't seem to be running at all. 

From the README, it seems we should be able to add a `semantic.yml` file with `enabled: false` to bypass the action. But we also need to add a replacement (the README also has alternatives. Must look at them)

**Comment by mcous** [comment]
@yanick do you have access to the repository settings? The "Semantic Pull Requests" requirement is set - and thus can be removed - via [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) on the `main` branch.

If not, do you know who we could ping that _does_ have admin access to the repo? This is gonna be quite annoying for continuing maintenance

**Comment by yanick** [comment]
I do, I do have access to the settings! \o/ I must have gotten those powers when I submitted changes to the documentation repo. I'll go and peek in the config after breakfast.

**Comment by mcous** [comment]
PRs have been running smoothly 🚢, I think we can call this one resolved

**Comment by yanick** [comment]
Yup. Closing!
