### ISSUE TITLE
svelte:options w/ svelte:element results in incorrect nodeName with render

### ISSUE THREAD

**Issue by seantimm** [testing-library/svelte-testing-library#201]
I'm creating some dynamic SVG content and using svelte:element to output the tags.  In order to avoid some rendering issues, I have to specify ```<svelte:options namespace="svg" />```.  As soon as I do this, the resultant nodeName I get from a render / query is "svelte:element" rather than "svg".  If I remove the ```<svelte:options>``` tag, the nodeName is properly returned as "svg".

**Comment by mcous** [comment]
@seantimm are you still experiencing this issue? This library is a very thin wrapper around Svelte's [client-side API](https://svelte.dev/docs/client-side-component-api), and there is nothing we're doing here to affect the element's `nodeName`. This likely was/is some issue in Svelte itself

**Comment by seantimm** [comment]
Not currently living in Svelte-land, unfortunately, but I believe you're correct, and I saw some changes come through on Svelte that addressed this.
