### ISSUE TITLE
Argument of type 'typeof SvelteComponentDev' is not assignable to parameter of type 'SvelteComponentDev'.

### ISSUE THREAD

**Issue by peterpeterparker** [testing-library/svelte-testing-library#203]
Hi,

Probably more a question than an issue per se but, I am a bit confuse about the new improved props typing for `render` function ([fb97676](https://github.com/testing-library/svelte-testing-library/commit/fb97676248a1628e395239a23c78e95c5896fede)) that was release in last version.

Given a component `Menu.svelte` when I try following:

```
const renderResult = render<Menu>(Menu);
```

I get following error:

>TS2345: Argument of type 'typeof SvelteComponentDev' is not assignable to parameter of type 'SvelteComponentDev'. Type 'typeof SvelteComponentDev' is missing the following properties from type 'SvelteComponentDev': $set, $on,  $destroy, $$prop_def, and 5 more. 

Am I missing something or should actually the `render` function accepts `typeof SvelteComponent` rather than `SvelteComponent`?

**Comment by yanick** [comment]
A new release with a potential fix (#204) was released a few moments ago. Can you give it a whirl and see if  it fixes this problem?

**Comment by peterpeterparker** [comment]
It works like a charm (tested locally and CI is green too). Thanks for the ultra fast fix!

**Comment by yanick** [comment]
W00t! Excellent. That typing is proving to be tricky. :sweat_smile:

**Comment by peterpeterparker** [comment]
Definitely! Went also back and forth between v3.2.0 and v3.2.1 to be sure i could reproduce the error and that it fixed it. Well played
