### ISSUE TITLE
How to test the reaction of a component which receives a dispatched component event?

### ISSUE THREAD

**Issue by jrh-webcraft** [testing-library/svelte-testing-library#208]
First of all, thanks for offering this great library!

I have a parent component which listens to a [component event](https://svelte.dev/tutorial/component-events) dispatched by a child component.

I know how to use `component.$on` to test that the dispatched event does the right thing *within the component which is dispatching*, [like so](https://www.thisdot.co/blog/component-testing-in-svelte#events).

But **I can't figure out how to test the reaction of the component which is dispatched to.**

Here's a basic example:

**Child.svelte**
```svelte
<script>
  import { createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()
  
  function handleSubmit(event) {
    dispatch('results')
  }
</script>

<form on:submit|preventDefault={ handleSubmit }>
  <button type='submit'>Submit</button>
</form>
```

**Parent.svelte**
```svelte
<script>
  import Child from './Child.svelte'

  let showResults = false

  function handleResults(event) {
    showResults = true
  }
</script>

<Child on:results={ handleResults } />

{ #if showResults }
  <p id='results'>Some results.</p>
{ /if }
```

The idea is to eventually write a test like:

```javascript
import { render } from '@testing-library/svelte'
import Parent from './Parent.svelte'

test('shows results when it receives them', () => {
  const rendered = render(Parent)
 
  // ***
  // Simulate the `results` event from the child component?
  // ***

  // Check that the results appear.
})
```

Can anyone advise, or let me know if I'm not thinking about this in a way that's idiomatic to this library?

This seems like such an essential thing to test that I'm surprised I'm not finding anything about it in the docs or searching the web in general. Makes me wonder if I'm missing something simple.

The easy workaround I can see is to just use stores and test that the child updates the store properly and the parent reacts to the store properly. But that would involve introducing a store when I don't really want to.

If `<Parent>` were reacting to a DOM event, I would use [fireEvent](https://testing-library.com/docs/dom-testing-library/api-events/).

But I don't know how I would get a hold of the `<Child>` component from the `<Parent>` test or how I would manually trigger the event (without actually submitting the form in `<Child>`).

(Just to test it out, I used `createEvent` to fire a custom `results` event on one of the DOM elements rendered by `<Child>` but it didn't seem to do anything.)

Does anyone know if there is a way with this library to test this all the way through using only component events?

Many thanks!

**Comment by basarbk** [comment]
This should work

```js
import { fireEvent, render, screen } from '@testing-library/svelte'
import Parent from './Parent.svelte'

test('shows results when it receives them', async () => {
  render(Parent)
  const buttonInChild = screen.getByRole('button', { name: 'Submit'});
  await fireEvent.click(buttonInChild);
  expect(screen.queryByText('Some results.')).toBeInTheDocument();
})
```
With testing library, your test code looks like a real user test steps.

**Comment by jrh-webcraft** [comment]
Thanks @basarbk.

It's sounding like the idiomatic approach is to treat the whole DOM tree as a whole, rather than considering each component a "unit" like in a traditional unit test.

It would be nice to be able to mock out Child, especially in the case where the actual Child component is complex (i.e. many form fields that would need to be filled out in order to fire the submit event). But I suppose that is a separate question, so I will close this out.

Cheers. :)
