### ISSUE TITLE
How to properly test context API

### ISSUE THREAD

**Issue by halafi** [testing-library/svelte-testing-library#209]
I haven't found much in docs, how can I pass context what normally would be done by a parent component?

if I do something like:
```
setContext('foo', {
    bar: { kek: 'bur' },
  });
 render(...);
```
I get an error: `Function called outside component initialisation`

and I haven't noticed a way to pass the context to render function call.

Is there any better way than creating a redundant component parent?

**Comment by danielfyhr** [comment]
This might work

```javascript
render(MyComponent, {
      context: new Map(Object.entries({ foo: { bar: { kek:'bur' } } }))
 })
```

**Comment by yanick** [comment]
@danielfyhr got it. I'm adding a test to the repo so that we keep that in mind somewhere.
