### ISSUE TITLE
 TestingLibraryElementError: no form control was found associated for Label and Input elements

### ISSUE THREAD

**Issue by nishav11** [testing-library/svelte-testing-library#215]
svelte testing library gives error while using getByLabelText for Textfield Component from SMUI. In the testing library It is mentioned that 'for' and 'id' for label and input elements are not required but still the test fails.

**Comment by yanick** [comment]
I just tried, and with the component

```
 <label> <span>Username 3</span> <input /> </label>
```

and the test file

```
import { expect, test } from 'vitest'

import { render } from '..'
import Comp from './fixtures/Label.svelte'

test('renders component into the document', () => {
  const { getByLabelText } = render(Comp)

  expect(getByLabelText('Username 3')).toBeInTheDocument()
})

```

everything works. Closing the issue, but feel free to reopen if you have an example showcasing the failure.
