### ISSUE TITLE
SvelteKit, `browser = false`

### ISSUE THREAD

**Issue by Mexican-Man** [testing-library/svelte-testing-library#217]
When reading `browser` from `import { browser } from '$app/environment';`, it always is `false`. Is this intentional? Since it is SvelteKit and not Svelte, I'm not sure if it falls within the scope of this library.

**Comment by Mexican-Man** [comment]
Right, but isn't the point of `jsdom` and `happy-dom` to test *as though* its in the browser? Would there be some way to override this behaviour? Or does this need to be injected elsewhere?

As a result, all components that aren't ssr/csr agnostic fail all tests, because they run the opposite of the way they're supposed to.

**Comment by yanick** [comment]
> Right, but isn't the point of `jsdom` and `happy-dom` to test _as though_ its in the browser? 

jsdom and happy-dom, yes. But that's several steps downstream of svelte and sveltekit rendering.

> Would there be some way to override this behaviour? Or does this need to be injected elsewhere?

My first thought would be to mock `$app/environment` and have it returns a `browser` set to `true`

**Comment by Mexican-Man** [comment]
What a simple solution, thank you.

`tests/mock.ts`

```ts
vi.mock('$app/environment', () => {
    return {
        browser: true,
    };
});
```

`vite.config.ts`

```diff
export default defineConfig(({ mode }) => {
    return {
        test: {
            globals: true,
+            setupFiles: ['./tests/mock.ts'],
        },
    },
}
```

This seems to do it.

**Comment by yanick** [comment]
W00t! Excellent!

**Comment by hyunbinseo** [comment]
Thanks for the solution. Works on the `esm-env` package as well.

https://github.com/benmccann/esm-env

```typescript
import { expect, test, vi } from 'vitest';

vi.mock('esm-env', () => ({ BROWSER: true }));
```

```svelte
<script>
  import { BROWSER } from 'esm-env'; // true
</script>
```
