### ISSUE TITLE
Add `"main"` to package.json

### ISSUE THREAD

**Issue by ivan-lednev** [testing-library/svelte-testing-library#265]
Hello,

I'm using the library with `eslint-plugin-import`, and it gives me grief because this library doesn't have the `"main"` field in `package.json`. 

I think adding it might save some time for people who might encounter the same error.

Thanks for a great library!

**Comment by matthieujabbour** [comment]
I have the same issue, adding `"main": "src/index.js",` to the `package.json` fixes it.

**Comment by yanick** [comment]
`main` field added. Hopefully it'll make eslint happy. :-)
