### ISSUE TITLE
Testing Form Input Value

### ISSUE THREAD

**Issue by Gil3co** [testing-library/svelte-testing-library#281]
### Description

I have a form, with `input` and `textarea` components, but when I want to check their values inside tests (that they are rendered properly, for example), I can't find the values.
Using `svelte`, `@testing-library/svelte` and `vitest`.

### Reproduction

I created a very minimal reproduction repo: https://github.com/Gil3co/form-test-values
Steps to reproduce:
1. Clone the repo.
2. Run `npm i`.
3. Run `npm run test`.

See that the text (`12`) is not found.
If you run `npm run dev` you will see the text in the browser.

Any help is appreciated

**Comment by yanick** [comment]
That's because `text` will look for text in the page, but in in values of input fields. Try

```
	expect(document.body.querySelector('input').value).toBe('12');
```

**Comment by Gil3co** [comment]
But shouldn't it be in the page itself?
It works in React for example - is Svelte different in that regard?
