### ISSUE TITLE
Property does not exist on type "Assertion<HTMLElement" error when using Typescript.

### ISSUE THREAD

**Issue by Wizzel1** [testing-library/svelte-testing-library#282]
I am trying to make the jest matchers work with typescript but for some reason I fail. 
I am using vitest and typescript so I added the https://github.com/testing-library/jest-dom#with-vitest step but I am a bit confused about the https://github.com/testing-library/jest-dom#with-typescript part. 

It says that I need to add 
```json
  // In tsconfig.json
  "include": [
    ...
    "./jest-setup.ts"
  ],
```

This is my current tsconfig.ts : 

```json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"moduleResolution": "bundler"
	}
	// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
	//
	// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
	// from the referenced tsconfig.json - TypeScript does not merge them in
}
``` 

and I don't know enough about tsconfigs to properly "copy over the relevant includes/excludes from the referenced json" and I am afraid that I will mess something up. 

Any tips how to handle this?

**Comment by yanick** [comment]
I don't have enough caffeine in the system to be able to think about the configuration interactions between typescript, vitest, jest, and testing-library, but this -- as a minimum -- seems to work for me:

```
import * as matchers from '@testing-library/jest-dom/matchers';
import {test, expect} from 'vitest';
import { render } from '@testing-library/svelte';

expect.extend(matchers);

import Comp from './+page.svelte';

test( 'basic', () => {
    const { findByTitle } = render(Comp);
    expect(1).toBeTruthy();
    expect( findByTitle('hi')).toHaveClass();
} )

```

**Comment by Wizzel1** [comment]
thanks @yanick for your answer. Unfortunately this didn't change anything. To clarify: My tests run as expected. I just get the above error from intellisense. 

I have 2 setup files for my tests:

src/vitest/registerMatchers.ts
 ```ts
import * as matchers from '@testing-library/jest-dom/matchers';
import { expect } from 'vitest';

expect.extend(matchers);
```
and src/vitest/cleanupDom.ts 
```ts
import { afterEach } from 'vitest';
import { cleanup } from '@testing-library/svelte';

afterEach(cleanup);
```
and I have added them to my vite.config.ts like this :

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
	plugins: [sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}'],
		reporters: ['verbose'],
		environment: 'jsdom',
		restoreMocks: true,
		setupFiles: [
			'./src/vitest/cleanupDom.ts',
			'./src/vitest/registerMatchers.ts'
		]
	}
});
```
so if I am not mistaken, that should to the same as what you suggested, right?

**Comment by yanick** [comment]
I think what confuses IntelliSense there is that you extend `expect` in your setup file, but in your test file proper you do

`import { expect } from 'vitest';`

so that's the one IntelliSense sees as being used.

For giggles, replaces line 1 in your test file with

```
import * as matchers from '@testing-library/jest-dom/matchers';
import {test, expect} from 'vitest';

expect.extend(matchers);
```

and see if IntelliSense sees the light.

**Comment by yanick** [comment]
Using @testing-library/jest-dom@6.2.1:

![image](https://github.com/testing-library/svelte-testing-library/assets/19954/a431126a-9979-4d56-a9e7-f067663d950b)

(this is neovim, not vs code, but the LSP underneath is the same)

**Comment by Wizzel1** [comment]
> Using @testing-library/jest-dom@6.2.1:
> 
> ![image](https://private-user-images.githubusercontent.com/19954/299057474-a431126a-9979-4d56-a9e7-f067663d950b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMTEwNTgsIm5iZiI6MTcwNjExMDc1OCwicGF0aCI6Ii8xOTk1NC8yOTkwNTc0NzQtYTQzMTEyNmEtOTk3OS00ZDU2LWE5ZTctZjA2NzY2M2Q5NTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE1MzkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiY2Q4YWI0OTZiYjY4NGYyMjQyZGY5MjRjM2JlOWM0MGY1NGU3MTU2YzIwMmM4MzBjNGVhYzYxZmM2NWEyYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mx-ABLCW0bvx2Y96E0xi1J0F4CZHtKpSiBMcZWb-POI)
> 
> (this is neovim, not vs code, but the LSP underneath is the same)

Thanks, I will check it again
