### ISSUE TITLE
Add ability to await fireEvent

### ISSUE THREAD

**Issue by EmilTholin** [testing-library/svelte-testing-library#30]
As was outlined in [this issue](https://github.com/testing-library/svelte-testing-library/issues/29), you sometimes need to wait for the next microtask to run before changes in the DOM have been flushed.

```javascript
const input = getByTestId('my-input');
fireEvent.input(input, {target: {value: 'some text'}});
// Wait for the next microtask for `value` to be 
// written to a potential bound variable
await tick();
// Check the value of the variable somehow
```

Maybe we could create a small abstraction over `fireEvent` from `dom-testing-library` and return a `tick` promise so that `fireEvent` can be awaited directly?

```javascript
const input = getByTestId('my-input');
await fireEvent.input(input, {target: {value: 'some text'}});
// Check the value of the variable somehow
```

```javascript
import {
  getQueriesForElement,
  prettyDOM,
  fireEvent as dtlFireEvent
} from '@testing-library/dom'
import { tick } from 'svelte'
export * from '@testing-library/dom'

export function fireEvent(...args) {
  dtlFireEvent(...args)
  return tick()
}
```

**Comment by alexkrolick** [comment]
Couple comments:
- fireEvent is wrapped in `act`, so it should flush some updates (depending on implementation)
- would it make sense to make it a "thenable" instead of a actual promise to avoid dangling promise chains in the tests?

**Comment by pngwn** [comment]
This isn't actually necessary due to how Svelte's updates work. Svelte batches updates and processes them in the next microtask, in order to ensure changes have been flushed to the DOM we can simply `await` the action that triggered the update like this:

```js
test('clicking the button should change the text', async () => {
  const { target, getByText } = render(Hello);

  const button = getByText('Change');
  const button2 = getByText('Change Again');
  const h1 = getByText('Hello World');

  await fireEvent.click(button);
  expect(h1.innerHTML).toBe('Hello Everybody');

  await fireEvent.click(button2);
  expect(h1.innerHTML).toBe('Hello Nobody');
});
```

This also works when performing multiple actions:

```js
test('updating Checkbox inputs should work', async () => {
  const inputs = getAllByLabelText(/Rice|Beans|Cheese|Guac/);
  const output = getByText(/Value CBG:/);

  await inputs.map(element => fireEvent.click(element));
  expect(output.innerHTML).toBe('Value CBG: Rice,Beans,Cheese,Guac (extra)');
});
```

I don't think this is a commonly known detail and perhaps warrants documentation, there may be times when this approach fails but a simple `await tick()` is always an option in such cases. Awaiting events like above should work in the majority of cases.

**Comment by alexkrolick** [comment]
I'm fairly certain awaiting something that is not a Promise does not have the effect you are describing - it just returns immediately as if the await wasn't there. I think we exolored this before @kentcdodds?

**Comment by kentcdodds** [comment]
I believe so. Either way what you really want to use is findBy and findAllBy queries instead of awaiting the fireEvent API.

**Comment by kentcdodds** [comment]
Actually, based on the example above what you probably should be doing is wrapping the assertion inside `wait`

**Comment by pngwn** [comment]
> I'm fairly certain awaiting something that is not a Promise does not have the effect you are describing - it just returns immediately as if the await wasn't there.

This is incorrect. Awaiting a non-promise/ thenable wraps the value in a promise or something to that effect. As I understand it, `await fn()` will always wait until the microtask queue is flushed regardless of what `fn` returns. So if `fn()` adds something to the microtask queue (in this case triggering some state change that adds a `flushUpdates` task to the queue) then there is no need to `fn(); await tick();`. Consider it a 'convenience hack', if you will, but it definitely works.

Regardless, the above code snippets are not theoretical examples but taken from actual tests that run and pass as expected, removing `await` breaks them, naturally. I personally feel that the ergonomics of awaiting the action that causes the update are better than using a helper function to wrap assertions in almost every test.

Examples of the aforementioned tests in action can be found [here](https://github.com/pngwn/svelte-test/blob/master/test/Hello.test.js) and [here](https://github.com/pngwn/svelte-test/blob/master/test/Input.test.js)

**Comment by kentcdodds** [comment]
Thanks for clarifying @pngwn 👍
