### ISSUE TITLE
Homepage link repository's "About" section points to wrong location

### ISSUE THREAD

**Issue by mcous** [testing-library/svelte-testing-library#326]
Link points to <https://testing-library.com/docs/dom-testing-library/intro>. It should point to <https://testing-library.com/docs/svelte-testing-library/intro>

<img width="475" alt="Screenshot 2024-02-19 at 3 10 43 PM" src="https://github.com/testing-library/svelte-testing-library/assets/2963448/a19b6442-472c-45a9-b208-b1e341d1bfd4">

**Comment by mcous** [comment]
@yanick did you see this one? Should be a quick fix. If you were able to give me some sort of repo access I'd be able to fix it up myself, too (and better triage issues etc.)

**Comment by yanick** [comment]
Oh my. Never noticed it. O.o  Good catch; fixed!
