### ISSUE TITLE
latest svelte@5 broke its tests

### ISSUE THREAD

**Issue by yanick** [testing-library/svelte-testing-library#353]
see #352

**Comment by mcous** [comment]
Weirdly enough, I cannot reproduce this failure locally on the same Svelte version

```
❯ npm why svelte
svelte@5.0.0-next.108 dev
```

I wonder if there's a race condition here? Maybe `tick()` isn't fully flushing updates, and that's what CI is hitting

**Comment by mcous** [comment]
More testing results:

- `svelte@5` accessor tests pass with `@sveltejs/vite-plugin-svelte@3.0.2`
- `svelte@5` accessor tests **fail** with `@sveltejs/vite-plugin-svelte@3.1.0`

Will add this to the thread over in svelte, too

**Comment by mcous** [comment]
Oh hm mothership issue has been closed with a fix that "preserves accessors with HMR." That's odd, because we have HMR disabled in our test suite. Will wait on the `next.109` release though and see what happens

**Comment by mcous** [comment]
@yanick looks like this has, in fact, been fixed upstream. Your report did the trick. I can no longer repro locally nor in CI

**Comment by yanick** [comment]
W00t! That was easy. ^.^
