### ISSUE TITLE
Investigate seeing the next version before the deploy

### ISSUE THREAD

**Issue by yanick** [testing-library/svelte-testing-library#356]
Right now, merges that aren't triggering a release don't show what would be the next version (I... think). See if we can tweak the semantic release action to always give us a head's up on what would be the next release, because I keep putting my deployment foot in my mouth, so to speak.

**Comment by mcous** [comment]
I was looking into the `dry-run` option for this! But I failed entirely to get it working locally so I gave up. But I agree this would be an excellent change if we could get it to work
