### ISSUE TITLE
Svelte 5: Context Issue

### ISSUE THREAD

**Issue by huntabyte** [testing-library/svelte-testing-library#358]
I'm not 100% sure if this issue lies with Svelte or Svelte Testing Library, but when attempting to test any component that calls `getContext` / `setContext`, the tests crash with an error.

![image](https://github.com/testing-library/svelte-testing-library/assets/64506580/33fdc4f9-5a5f-4d25-a889-839e71c134cb)

I've created a simple reproduction to demonstrate this:
[Reproduction StackBlitz](https://stackblitz.com/github/huntabyte/svelte-5-testing-lib-reproduction?file=README.md) - just run `pnpm test` 
[Reproduction Repo](https://github.com/huntabyte/svelte-5-testing-lib-reproduction)

**Comment by mcous** [comment]
Your `vite.config.js` file is not configured to load Svelte's browser code. You can see that the stacktrace is pointing to Svelte's server code: `svelte/src/internal/server/context.js`.

See the [Vitest setup docs](https://testing-library.com/docs/svelte-testing-library/setup#vitest) for proper Vitest setup to ensure Svelte's browser version is used

**Comment by huntabyte** [comment]
Ah, I see! I've added that conditional, yet it still seems to try to use the `server/context.js` 🤔

**Comment by huntabyte** [comment]
Using this method solved this issue for me, thank you!

https://github.com/testing-library/svelte-testing-library/issues/222#issuecomment-1910217975
