### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by benmccann** [testing-library/svelte-testing-library#385]
The currently released version is pulling in an bloated version of `aria-query` that has about 50 unnecessary dependencies (https://github.com/A11yance/aria-query/pull/497). This has been fixed on `main`, but not yet released. Would you be able to release a new version? Thanks!

**Comment by mcous** [comment]
I suspect you may have higher perms than me in this repo 🫠. But sure! The `next` branch is ready to go anyway, so I'll merge it in which should trigger the 5.2.0 release

Looks like the DOM testing library version is question was bumped in a `chore` commit; I'll see if I can tweak the dependabot config to prevent this issue in the future

**Comment by benmccann** [comment]
thanks!!
