### ISSUE TITLE
Unable to get value of modified props back from component in svelte 5

### ISSUE THREAD

**Issue by lachlancollins** [testing-library/svelte-testing-library#394]
## Problem

Hi there, I'm struggling to replicate some functionality that @tanstack/svelte-query used with svelte v4. We passed a store into the component's props, and then accessed that store from the test to ensure the query had the right state at different points in its lifecycle: https://github.com/TanStack/query/blob/38e5c4b85b0d1de23e8fd5a5661be30e9b255a86/packages/svelte-query/tests/createQuery/createQuery.test.ts#L36-L65

With svelte v5, I would assume the equivalent behaviour would be to create a `$state` signal within the test, pass that signal into the component, modify it, and then read the value back in the test. Unfortunately, the value doesn't seem to get passed back to the test. I've tried marking the prop as `$bindable()`, but this doesn't seem to do anything.

Any advice on this would be much appreciated!

Related: https://github.com/TanStack/query/pull/6981

## Minimal Repro

https://codesandbox.io/p/devbox/testing-library-svelte-repro-xmxqn4

1. Run `pnpm run test`
2. `tests/stores.test.ts` will pass, but `tests/runes.svelte.test.ts` will fail the equivalent test

**Comment by mcous** [comment]
Hey @lachlancollins, I messed around with this a little, and I'm thinking this might be a fundamental limitation of Svelte's client side API that this testing library lightly wraps. There was no good way to test directly `bind` in Svelte 4, and I think that might still be the case: information can't bubble back up to the test through `props` directly.

(At first I thought the problem might lie with some trickery we do on our end: we wrap all `props` in our own `$state` signal to be able to `rerender`. However, removing that wrapper and passing props directly to `mount` did not change the outcome of the test.)

One thing that _did_ work for me was wrapping the signal up in a little "box." Would this be a viable strategy for this test/functionality?

```ts
import { fireEvent, render, waitFor } from '@testing-library/svelte'
import { describe, expect, test } from 'vitest'

import Subject from './fixtures/RunesState.svelte'

// Wrap counter state and actions
const createCounter = () => {
  let count = $state(0)
  const increment = () => (count += 1)

  return {
    get count() {
      return count
    },
    increment,
  }
}

describe('runes', () => {
  test('Test click event', async () => {
    const counter = createCounter()
    const rendered = render(Subject, { counter })

    await waitFor(() => rendered.getByText('Count: 0'))
    await fireEvent.click(rendered.getByRole('button', { name: /Increment/i }))
    await waitFor(() => rendered.getByText('Count: 1'))

    expect(counter.count).toEqual(1)
  })
})
```

```svelte
<script lang="ts">
  interface Counter {
    count: number,
    increment: () => void
  }

  let { counter }: { counter: Counter} = $props()
</script>

<button onclick={() => counter.increment()}>Increment</button>

<div>Count: {counter.count}</div>
```

One other thing to look out for is that signals of object values behave differently that signals of primitive values, returning `Proxy`s of the objects in question. [`$state.snapshot`](https://svelte-5-preview.vercel.app/docs/runes#$state-snapshot) may have to be involved in any tests of object state

I have a pretty vested interest in Svelte 5 support for `svelte-query`, so feel free to hit me up in Discord in the testing-library channel or via DM if chatting through things there is easier

**Comment by mcous** [comment]
Uh weirdly enough, this also works, no `$state` required:

```svelte
<script>
  let { counter } = $props()
</script>

<button onclick={() => (counter.count += 1)}>Increment</button>
<p data-testid="count">Count: {counter.count}</p>
```

```js
import { fireEvent, render, screen } from '@testing-library/svelte'
import { describe, expect, test } from 'vitest'

import Subject from './fixtures/Counter.svelte'

describe('runes', () => {
  test('Test click event', async () => {
    const counter = { count: 0 }
    render(Subject, { counter })

    const button = screen.getByText(/increment/iu)
    const countMessage = screen.getByTestId('count')

    expect(countMessage).toHaveTextContent('Count: 0')
    await fireEvent.click(button)
    expect(countMessage).toHaveTextContent('Count: 1')

    expect(counter).toEqual({ count: 1 })
  })
})
```

I'm still coming up to speed on runes, and I don't have a good intuition for the implicit magic involved compared to store or explicit userland signals. I'll try to looks at the PR you linked above later in the day and see if I have any ideas

**Comment by lachlancollins** [comment]
Thanks so much for your quick reply @mcous ! It seems like passing in any object or array will make it deeply reactive, regardless of if it was defined with a rune!

This is actually causing a _different_ issue for our tests, and our current solution is a bit messy. I might contact you on the discord channel to continue the discussion :)

**Comment by lachlancollins** [comment]
I've got this working most reliably by using getter/setters. When trying to use some `untrack()` logic, I found that the basic `$state` signal was no longer getting updated. However, the getter/setter pattern means that any time the value is set, it updates at the test level first, then propagates down to the component (no need for `$bindable` either!)

**Comment by mcous** [comment]
Glad to hear it! I think that tracks pretty well with existing Svelte 5 examples, too. Please reach out if anything else pops up
