### ISSUE TITLE
Example in readme doesn't work

### ISSUE THREAD

**Issue by antony** [testing-library/svelte-testing-library#43]
I've not yet succeeded in getting any of it to work, but, based on my experiments:

1. Need to import 'fireEvent' from '@testing-library/svelte'
1. Need to import 'waitForElement' from '@testing-library/svelte'
1. Need to install `@testing-library/jest-dom` in order to get 'toBeInTheDocument' matcher - this is in the docs, but it shouldn't be required for the *basic* example.

**Comment by benmonro** [comment]
Would love a PR if you can fix it

**Comment by oieduardorabelo** [comment]
i believe this issue was fixed by #44 @benmonro
