### ISSUE TITLE
Request: Support for shallow snapshot tests

### ISSUE THREAD

**Issue by ohager** [testing-library/svelte-testing-library#49]
I'm not sure if it's even possible, but did you already consider support for shallow rendering, especially for snapshot testing.

**Comment by benmonro** [comment]
Hi @ohager, unfortunately shallow rendering goes against [the guiding principles](https://github.com/testing-library/svelte-testing-library#guiding-principles) of testing-library, and snapshot testing of UI code is (in my experience) manual testing (performed at PR time) and should be avoided.

**Comment by ohager** [comment]
@benmonro Understand your point. I pretty much like snapshot testing, but will use your point to reflect. Thanks for fast response and insight.

**Comment by benmonro** [comment]
Snapshot testing is good when you inherit an untested code base and need to refactor.  But they should be thrown away as they are characterization tests

**Comment by ohager** [comment]
In former react projects I had pretty good results with snapshot testing. Although, snapshot testing was just a part of the entire test stack. Shallow rendering was a crucial strategy for snapshots, because I was able to isolate the components, and could write tests very fast; no need of complex mocking, low impact on PRs when changing a single component etc.  - I know, that snapshot tests have their drawbacks, especially `jest -u` I appreciate your feedback.Ty

**Comment by benmonro** [comment]
Well... Consider what it does to the readability if the tests, the fact that you can't do tdd and the fragility it adds.  My colleague put it best.  Snapshot testing is like cocaine. It feels good at first but the more you do it the more it destroys your life and the life of those around you.  🙂
