### ISSUE TITLE
Issue: custom queries option is disregarded when passed to render function

### ISSUE THREAD

**Issue by Odedgefen** [testing-library/svelte-testing-library#52]
Hey,
Trying to enrich the global queries as based on code snippet in official docs doesn't work

```
import { render, queries } from '@testing-library/svelte' 
import * as customQueries from './custom-queries'`

const customRender = (ui, options) =>
  render(ui, { ...options, queries: { ...queries, ...customQueries }})

// re-export everything
export * from '@testing-library/react'

// override render method
export { customRender as render }
```

It looks like queries in options are not passed to the getQueriesForElement as second parameter:
https://github.com/testing-library/svelte-testing-library/blob/master/src/index.js#L23

**Comment by mihar-22** [comment]
Hey @Odedgefen just letting you know this has been resolved in the recent update. You can pass it into the `render` function as the third parameter `render(Component, ComponentOptions, RenderOptions)`. Enjoy!
