### ISSUE TITLE
How to coverage each, alt and slot

### ISSUE THREAD

**Issue by marlonmleite** [testing-library/svelte-testing-library#55]
I write my tests and even passing the line is not considered correct coverage, did anyone solve it?
![image](https://user-images.githubusercontent.com/8551142/66484388-458a1680-ea7d-11e9-96bc-65f3e5784998.png)

**The same problem goes for alt in img.**
![image](https://user-images.githubusercontent.com/8551142/66484533-884bee80-ea7d-11e9-9035-e31a2c2f1f0f.png)

**The same problem goes for slot attr.**
![image](https://user-images.githubusercontent.com/8551142/66484460-65b9d580-ea7d-11e9-8d59-7c7254df5403.png)

**Comment by mihar-22** [comment]
Hey @marlonmleite it's really hard to tell from what you've posted. I'd need to see your components and test files. Most the statements have been called (indicated by the gutter numbers), except the `Thumb` component. It could be a problem with the tests you wrote. Try seeing if those lines of code are being executed when you call the svelte compiled code directly, not in any tests. If they are then most likely there's an issue with the svelte compilation that the coverage framework doesn't pick up on.

**Comment by mihar-22** [comment]
Closing this issue for now, try out the Svelte discord if you have any other questions.

Invite Link: https://discordapp.com/invite/yy75DKs
