### ISSUE TITLE
[Feature] Enable to query by component name like EnzymeJS shallow.find()

### ISSUE THREAD

**Issue by vuphan365** [testing-library/svelte-testing-library#86]
Hi,

I am working with svelte-test-library, but I found it hard to check did component render or not by Dom Testing Library. So it 's a pleasure if you could implement a feature to return the component by name like EnzymeJS shallow.find()

Thank you

**Comment by benmonro** [comment]
@vuphan365 the testing library guiding principles are centered around not using implementation details like component name and/or shallow rendering in tests.

https://testing-library.com/docs/guiding-principles

https://kentcdodds.com/blog/why-i-never-use-shallow-rendering
