### ISSUE TITLE
Customize the container

### ISSUE THREAD

**Issue by EmilTholin** [testing-library/svelte-testing-library#9]
Since a Svelte component is compiled, it's a little bit harder to be flexible with what elements should wrap the component than what it is in e.g. React where you can wrap your component with some custom JSX directly inline in the test.

With this in mind, what do you think about taking some [inspiration from `react-testing-library`](https://github.com/testing-library/react-testing-library/blob/master/src/index.js#L33-L38) and allowing the user to customize the `target` themselves?

```diff
- export const render = (Component, options) => {
+ export const render = (Component, { target, ...options }) => {
+   if (!target) {
+     target = document.body.appendChild(document.createElement('div'))
+   }

   // ...
 }
```

```javascript
test('it renders properly in a table', async () => {
  const table = document.createElement('table')
  document.body.appendChild(table)

  const utils = render(MyTableBody, {target: table})

  // ...
})
```

**Comment by benmonro** [comment]
You read my mind.  My plan was to add that.
