### ISSUE TITLE
Mocking svelte transitions in Jest

### ISSUE THREAD

**Issue by ritchieanesco** [testing-library/svelte-testing-library#99]
I've been trying to figure out how to mock transitions as they seem to mess up my unit test.
For context, `slide` animates **in** and `fade` animates **out** an element. I've tried the following
code but it looks like setting `duration` to zero prevents the transition from completing therefore
leaving two elements on the page

```js
jest.mock("svelte/transition", () => {
  const fakeTransitions = {
    delay: 0,
    duration: 0,
    easing: x => x,
    css: false,
  }
  return {
    slide: () => {
      return {
        ...fakeTransitions,
      }
    },
    fade: () => {
      return {
        ...fakeTransitions,
      }
    },
  }
})

it("should swap elements on click", async () => {
  render(Component)
  expect(screen.getByTestId("item-a")).toBeInTheDocument()
  await fireEvent.click(screen.getByText(/button/i))
  await waitFor(() =>
    expect(screen.getByTestId("item-b")).toBeInTheDocument(),
  )
  expect(screen.queryByTestId("item-a")).not.toBeInTheDocument()
})
```

Thoughts on how to handle svelte transitions in tests?

**Comment by MirrorBytes** [comment]
This doesn't have to do with transitions. Since you're using the same exact props for your transitions, you need to set them up the same way, i.e.:

```javascript
await waitFor(() => { ... });
```

**Comment by ritchieanesco** [comment]
@MirrorBytes can you elaborate? Providing a waitFor with spread operator doesn’t illustrate anything. I’d like to see how you would write unit tests where transitions have been mocked so it doesn’t add valuable time in CI.

**Comment by MirrorBytes** [comment]
It's not a spread, it's a filler that represents existing (yet arbitrary) code used in examples, meaning you have to wrap your `expect` statements the same way.

```javascript
  render(Component)
  await waitFor(() =>
    expect(screen.getByTestId("item-a")).toBeInTheDocument()
  )
  await fireEvent.click(screen.getByText(/button/i))
  await waitFor(() =>
    expect(screen.getByTestId("item-b")).toBeInTheDocument(),
  )
  await waitFor(() =>
    expect(screen.queryByTestId("item-a")).not.toBeInTheDocument(),
  )
```

And if that doesn't work, throw an `await tick` between them:

```javascript
  render(Component)
  await waitFor(() =>
    expect(screen.getByTestId("item-a")).toBeInTheDocument()
  )
  await fireEvent.click(screen.getByText(/button/i))
  await waitFor(() =>
    expect(screen.getByTestId("item-b")).toBeInTheDocument(),
  )
  await tick()
  await waitFor(() =>
    expect(screen.queryByTestId("item-a")).not.toBeInTheDocument(),
  )
```

**Comment by ritchieanesco** [comment]
@MirrorBytes thanks for responding however this doesn’t resolve my issue with mocking out transitions.

**Comment by MirrorBytes** [comment]
@ritchieanesco Ok, let me play around with transitions for a bit. I'll be able to give a more accurate fix later.

**Comment by MirrorBytes** [comment]
@ritchieanesco Here's what I came up with:

## `App.svelte`
```html
<script lang="ts">
  import { slide, fade } from 'svelte/transition';
  import { cubicOut, linear } from 'svelte/easing';

  export let slide_props = {
    delay: 0,
    duration: 0,
    easing: cubicOut,
  };
  export let fade_props = {
    delay: 0,
    duration: 0,
    easing: linear,
  };

  let toggle = false;
</script>

{#if !toggle}
<div transition:slide={slide_props} class="item-a">
  Item A
</div>
{/if}

{#if toggle}
<div transition:fade={fade_props} class="item-b">
  Item B
</div>
{/if}

<button on:click={() => (toggle = !toggle)}>Click Me!</button>
```

## `app.spec.ts`
```typescript
import { waitFor } from '@testing-library/dom';
import { render, fireEvent } from '@testing-library/svelte';

import App from '../App.svelte';

test('should swap elements on click', async () => {
  const { getByText } = render(App);

  expect(() => getByText('Item A')).not.toThrow();
  expect(() => getByText('Click Me!')).not.toThrow();

  const button = getByText('Click Me!');

  await fireEvent.click(button);

  await waitFor(() => {
    expect(() => getByText('Item A')).toThrow();
  });

  expect(() => getByText('Item B')).not.toThrow();
});
```

In mine, `jest-dom` is not required. And you can pass custom props for the dev/prod environment (or vice versa).

**Comment by MirrorBytes** [comment]
Also, Typescript isn't required, it's just apart of my test environment.

**Comment by ritchieanesco** [comment]
Thanks @MirrorBytes... i guess I might as well just use env variables to set falsey transition values which can be tree shaken.

**Comment by MirrorBytes** [comment]
For prod? That wouldn't do much considering the values are not considered
dead code in svelte. Set your prod values, and provide falsey values in the
`render` call in the tests. The test time and prod size changes caused by
them are negligible at most.

Also, as an explanation for the optional props, I will always recommend
avoiding mocks unless absolutely necessary as they could result in false
positives.

In your provided mock, you were overriding the transition functions, not
just the params, which caused your problem most likely. You would have to
recreate the transition functions in order to mock them effectively...
Which would arguably take more time for tests to run.

**Comment by ritchieanesco** [comment]
Thnx for your help... coming from react this is how I would have mocked any third party.... I understand that time taken for setting up and tearing down indicates a code smell but was hoping that I didn’t have to modify implementation  just to make my tests work.. might raise it in svelte itself and see what those guys say

**Comment by MirrorBytes** [comment]
You can mock the transition functions, but you'd have to completely mock
them.. Not just their parameters, that's what I was getting at if you don't
want to mess with your implementation.

This would be no different in react in terms of mocking transition
functions.

**Comment by ritchieanesco** [comment]
Thnx @MirrorBytes will probably have to do that..

**Comment by MirrorBytes** [comment]
I'll play around with some mock implementations tomorrow afternoon that
might be able to help. You may be able to use the original functions with
custom params in the mocks to bypass messing with your implementation.

**Comment by ritchieanesco** [comment]
Thanks so much for your help @MirrorBytes

**Comment by MirrorBytes** [comment]
So you were on the right track initially, as this is the only configuration that I could get to work without the props:

## `app.spec.ts`
```typescript
jest.mock('svelte/transition', () => ({
  slide: () => ({
    delay: 0,
    duration: 0,
  }),
  fade: () => ({
    delay: 0,
    duration: 0,
  }),
}));

import { waitFor } from '@testing-library/dom';
import { render, fireEvent } from '@testing-library/svelte';

import App from '../App.svelte';

test('should swap elements on click', async () => {
  const { getByText } = render(App);

  expect(() => getByText('Item A')).not.toThrow();
  expect(() => getByText('Click Me!')).not.toThrow();

  const button = getByText('Click Me!');

  await fireEvent.click(button);

  await waitFor(() => {
    expect(() => getByText('Item A')).toThrow();
  });

  expect(() => getByText('Item B')).not.toThrow();
});
```

## `App.svelte`
```html
<script lang="ts">
  import { slide, fade } from 'svelte/transition';

  let toggle = false;
</script>

{#if !toggle}
<div transition:slide class="item-a">
  Item A
</div>
{/if}

{#if toggle}
<div transition:fade class="item-b">
  Item B
</div>
{/if}

<button on:click={() => (toggle = !toggle)}>Click Me!</button>
```

**Comment by ritchieanesco** [comment]
@MirrorBytes thanks for taking a look. Yes, i got this to work with the latest version of svelte... this looks like an issue with svelte 3.29.0.

**Comment by MirrorBytes** [comment]
Ahh, yes. 3.29.0 and 3.30 had a few bugs that made projects fail to run after compiling. Glad you resolved your issue.
